USE storyafrika;
-- Insert Stories
INSERT INTO stories (id, title, text, User, created_at, updated_at, image) VALUES
(uuid(), 'The Power of Education', 'Education can transform lives. Through years of teaching in rural areas, I have witnessed firsthand how access to quality education can uplift communities. It gives children the tools to dream big and equips them with the skills to pursue their goals. Every child deserves this chance.', (SELECT id FROM users WHERE username = 'yusuf_teacher'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'A Journey of Resilience', 'This story is about a woman who faced insurmountable odds yet emerged victorious. From growing up in a war-torn region to becoming a leader in her community, her journey is a testament to the strength and resilience of the human spirit. Her story is one of hope and determination.', (SELECT id FROM users WHERE username = 'aminabello'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'Innovating for Change', 'How technology is changing lives in Africa. In regions where resources are scarce, innovation is not just a luxury, but a necessity. This story explores various technological advancements that are helping to solve problems in healthcare, education, and agriculture, bringing about a new wave of change.', (SELECT id FROM users WHERE username = 'chiamaka89'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'Finding My Passion', 'My journey to becoming an artist. It wasn’t easy finding my path, but through dedication and a lot of hard work, I was able to turn my passion for art into a fulfilling career. This story delves into the challenges I faced and the lessons I learned along the way.', (SELECT id FROM users WHERE username = 'aminabello'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'Building a Business', 'Challenges and triumphs of entrepreneurship. Starting a business in Africa comes with its own set of challenges, from limited access to funding to navigating complex regulatory environments. This story highlights the perseverance required to succeed and the triumphs that make the journey worthwhile.', (SELECT id FROM users WHERE username = 'chiamaka89'), NOW(), NOW(), 'https://unsplash.it/600');



-- Insert More Stories
INSERT INTO stories (id, title, text, user_id, created_at, updated_at, image) VALUES
(uuid(), 'Exploring the Unknown', 'Exploring the Unknown takes you on a journey through the most remote and mysterious places on Earth. It delves into the adventures and discoveries made by explorers who dared to venture into the unknown, facing numerous challenges along the way.', (SELECT id FROM users WHERE username = 'john_doe'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'The Last Frontier', 'The Last Frontier explores the vast and uncharted territories that remain on our planet. From the deepest oceans to the highest mountains, this story captures the spirit of adventure and the drive to explore the unknown.', (SELECT id FROM users WHERE username = 'jane_doe'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'Innovations in Medicine', 'Innovations in Medicine showcases the latest advancements in medical science and technology. It highlights breakthrough treatments and technologies that are revolutionizing healthcare and improving patient outcomes.', (SELECT id FROM users WHERE username = 'mary_jane'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'Journey to the Stars', 'Journey to the Stars is a captivating story about the quest to explore space. It details the challenges and triumphs of space exploration, from the early days of rocketry to the latest missions to distant planets and beyond.', (SELECT id FROM users WHERE username = 'peter_parker'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'The Rise of AI', 'The Rise of AI explores the rapid development of artificial intelligence and its impact on society. It examines how AI is transforming industries, improving lives, and raising important ethical questions.', (SELECT id FROM users WHERE username = 'tony_stark'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'Climate Change Warriors', 'Climate Change Warriors tells the inspiring stories of individuals and organizations fighting to combat climate change. It highlights their efforts to protect the environment and promote sustainable practices.', (SELECT id FROM users WHERE username = 'bruce_wayne'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'The Digital Revolution', 'The Digital Revolution examines the profound changes brought about by digital technology. It explores how digital innovations are reshaping industries, economies, and our daily lives.', (SELECT id FROM users WHERE username = 'clark_kent'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'Breaking Barriers', 'Breaking Barriers is a story about individuals who have overcome significant obstacles to achieve their dreams. It celebrates their resilience and determination, showcasing their inspiring journeys.', (SELECT id FROM users WHERE username = 'diana_prince'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'The Future of Work', 'The Future of Work explores how automation and digitalization are changing the nature of work. It looks at the opportunities and challenges these changes present and what they mean for the workforce of tomorrow.', (SELECT id FROM users WHERE username = 'steve_rogers'), NOW(), NOW(), 'https://unsplash.it/600'),
(uuid(), 'Art in the Digital Age', 'Art in the Digital Age examines how digital technology is transforming the world of art. It highlights how artists are using digital tools to create innovative works and reach new audiences.', (SELECT id FROM users WHERE username = 'natasha_romanoff'), NOW(), NOW(), 'https://unsplash.it/600');
