# Generated by Django 5.2.11 on 2026-02-08 02:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentGuideline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed explanation of this guideline"
                    ),
                ),
                (
                    "good_examples",
                    models.TextField(
                        blank=True,
                        help_text="Examples of content that follows this guideline",
                    ),
                ),
                (
                    "bad_examples",
                    models.TextField(
                        blank=True,
                        help_text="Examples of content that violates this guideline",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Content Guideline",
                "verbose_name_plural": "Content Guidelines",
                "db_table": "content_guidelines",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="EditorialNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField()),
                ("is_urgent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Editorial Note",
                "verbose_name_plural": "Editorial Notes",
                "db_table": "editorial_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedStory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                (
                    "custom_headline",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom headline for homepage",
                        max_length=255,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave empty for indefinite featuring",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Featured Story",
                "verbose_name_plural": "Featured Stories",
                "db_table": "featured_stories",
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_progress", "In Progress"),
                            ("approved", "Approved"),
                            ("needs_revision", "Needs Revision"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Detailed feedback for the writer"
                    ),
                ),
                (
                    "meets_editorial_standards",
                    models.BooleanField(
                        default=False,
                        help_text="Does the story meet StoryAfrika's editorial standards?",
                    ),
                ),
                (
                    "cultural_sensitivity_check",
                    models.BooleanField(
                        default=False,
                        help_text="Story respects cultural and personal dignity",
                    ),
                ),
                (
                    "originality_check",
                    models.BooleanField(
                        default=False, help_text="Content is original or properly cited"
                    ),
                ),
                (
                    "completeness_check",
                    models.BooleanField(
                        default=False,
                        help_text="Story reads as complete, not a social post",
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Story Review",
                "verbose_name_plural": "Story Reviews",
                "db_table": "story_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "revision_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about what was changed in this revision",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Story Revision",
                "verbose_name_plural": "Story Revisions",
                "db_table": "story_revisions",
                "ordering": ["-created_at"],
            },
        ),
    ]
