# Generated by Django 5.2.11 on 2026-02-08 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("editorial", "0001_initial"),
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentguideline",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guidelines_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="editorialnote",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="editorial_notes_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="editorialnote",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editorial_notes",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="featuredstory",
            name="featured_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="featuredstory",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="featured_placements",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="storyreview",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="story_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storyreview",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="storyrevision",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="editorial.storyreview",
            ),
        ),
        migrations.AddField(
            model_name="storyrevision",
            name="revised_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="story_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storyrevision",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="stories.story",
            ),
        ),
        migrations.AddIndex(
            model_name="featuredstory",
            index=models.Index(
                fields=["is_active", "position"], name="featured_st_is_acti_57bda4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storyreview",
            index=models.Index(
                fields=["story", "status"], name="story_revie_story_i_61edb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storyreview",
            index=models.Index(
                fields=["reviewer", "status"], name="story_revie_reviewe_27ab38_idx"
            ),
        ),
    ]
