# Generated by Django 5.2.11 on 2026-02-08 02:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReadingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_reading", models.BooleanField(default=False)),
                ("time_spent_seconds", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Reading Session",
                "verbose_name_plural": "Reading Sessions",
                "db_table": "reading_sessions",
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "content",
                    models.TextField(help_text="Story content in Markdown format"),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True, help_text="Auto-generated HTML from Markdown"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Brief excerpt or summary (auto-generated if empty)",
                        max_length=500,
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="story_images/"),
                ),
                ("hero_image_caption", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted for Review"),
                            ("in_review", "In Review"),
                            ("needs_revision", "Needs Revision"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured on homepage by editors"
                    ),
                ),
                ("featured_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("word_count", models.IntegerField(default=0)),
                ("reading_time_minutes", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
                "db_table": "stories",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
