# Generated by Django 5.2.11 on 2026-02-08 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stories", "0001_initial"),
        ("taxonomy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="readingsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reading_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stories",
                to="taxonomy.category",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stories",
                to="taxonomy.country",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="era",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="taxonomy.era",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="themes",
            field=models.ManyToManyField(
                blank=True, related_name="stories", to="taxonomy.theme"
            ),
        ),
        migrations.AddField(
            model_name="readingsession",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_sessions",
                to="stories.story",
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["status", "-published_at"], name="stories_status_118e3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["category", "status"], name="stories_categor_56f0c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["country", "status"], name="stories_country_59dc7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["author", "status"], name="stories_author__d94e14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readingsession",
            index=models.Index(
                fields=["story", "started_at"], name="reading_ses_story_i_5d969b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="readingsession",
            index=models.Index(
                fields=["user", "started_at"], name="reading_ses_user_id_5af35b_idx"
            ),
        ),
    ]
